# BNF from sequelize due to issue #8
# This package does not own any rights to this BNF

# Entry points
## Used when parsing the attribute
attribute ::= ( ...association | ...identifier ) jsonpath? castormodifiers?;

## Used when parsing a nested JSON path used inside of an attribute
## Difference with "attribute" is in the first part. Instead of accepting:
##  $association.attribute$ & attribute
## It accepts:
##  key, "quotedKey", and [0] (index access)
partialjsonpath ::= ( ...indexaccess | ...key ) jsonpath? castormodifiers? ;

# Internals
identifier ::= ( "A"->"Z" | "a"->"z" | digit | "_" )+ ;
digit ::= "0"->"9" ;
number ::= ...digit+ ;
association ::= %"$" identifier ("." identifier)* %"$" ;
jsonpath ::= ( ...indexaccess | ...keyaccess )+ ;
indexaccess ::= %"[" number %"]" ;

keyaccess ::= %"." key ;
	nonemptystring ::= ...(%"\\" (anyexceptquoteorbackslash | escapedcharacter)+ %"\\") ;
	key ::= nonemptystring | ( "A"->"Z" | "a"->"z" | digit | "_" | "-" )+ ;
escapedcharacter ::= %"\\\\" ( "\\" | "\\\\" );
any ::= !"" ;
anyexceptquoteorbackslash ::= !("\\" | "\\\\");
castormodifiers ::= (...cast | ...modifier)+;
cast ::= %"::" identifier ;
modifier ::= %":" identifier ;
