name: Reflection Test (via NPM)

concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  run-linux:

    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          path: 'temp-repo'

      - name: Sparse Checkout
        run: |
          cd temp-repo
          git sparse-checkout init --cone
          git sparse-checkout set test

      - name: Setup NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install NPM Dependencies
        run: npm install bnf-parser -g

      - name: Automated tests
        run: node ./temp-repo/test/index.js
        working-directory: ./temp-repo/test