name: Reflection Test (via NPM)

# This configuration cancels previous runs if a new run is started on the same branch/PR. Only one run at a time per PR.
# from https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#example-using-a-fallback-value
concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  run-linux:

    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v3

      - name: Setup NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install NPM Dependencies
        run: npm install bnf-parser -g

      - name: Automated tests
        run: npm run test