name: Reflection Test (via NPM)

on:
  push:
    branches: [ master ]

jobs:
  run-linux:
    if: ${{ false }}  # disable for now

    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v3

      - name: Setup NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install NPM Dependencies
        run: npm install bnf-parser

      - name: Automated tests
        run: npm run test