name: Test

on:
  push:
    branches: [ main, unstable ]
  pull_request:
    branches: [ main, unstable ]

jobs:
  run-linux:

    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v3

      - name: Setup NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install NPM Dependencies
        run: npm install

      - name: Install bnf-parser
        run: npm install . -g

      - name: Link local package
        run: npm link bnf-parser

      - name: Build the library
        run: npm run build

      - name: Automated tests
        run: npm run test